# Generated by Django 3.1.3 on 2021-03-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210324_1239'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='checkouts',
            table='school_checkouts',
        ),
    ]
