# Generated by Django 3.1.3 on 2021-03-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='phone',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
