# Generated by Django 3.1.3 on 2021-03-28 09:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210328_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c17b728c-8fab-11eb-8bd9-acde48001122'), editable=False, primary_key=True, serialize=False),
        ),
    ]
