# Generated by Django 3.1.3 on 2021-05-13 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210328_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f7443be0-b405-11eb-b6a7-ac1203cf8108'), editable=False, primary_key=True, serialize=False),
        ),
    ]
