# Generated by Django 3.1.3 on 2021-05-13 16:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210513_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f9f0f50b-b406-11eb-92ee-ac1203cf8108'), editable=False, primary_key=True, serialize=False),
        ),
    ]
