# Generated by Django 3.1.3 on 2021-05-13 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210513_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6f49e2c4-b408-11eb-b14a-ac1203cf8108'), editable=False, primary_key=True, serialize=False),
        ),
    ]
