# Generated by Django 3.1.3 on 2021-05-31 05:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20210324_1239'),
        ('orders', '0007_auto_20210513_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='additional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1d1afb46-c1d2-11eb-8274-acde48001122'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.schools'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.classes'),
        ),
    ]
