# Generated by Django 3.1.3 on 2021-06-03 06:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210531_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.UUIDField(default=uuid.UUID('97a0ac28-c432-11eb-b52b-acde48001122'), editable=False, primary_key=True, serialize=False),
        ),
    ]
